apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=azure
        - --email-domain=microsoft.com
        - --upstream=http://10.0.83.95:80
        - --http-address=0.0.0.0:4180
        - --azure-tenant=<insert your azure ad tenant/directory id here>
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: <insert your azure ad app client id here>
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: "<insert your azure ad app secret here>"
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: <you could run python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'>
        image: docker.io/colemickens/oauth2_proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
